package iso3166.part1;
@:enum abstract Alpha2(String) to String {
	@:to
	public function toAlpha3():Alpha3 return switch ((cast this : Alpha2)) {
		case AF:Alpha3.AFG;
		case AL:Alpha3.ALB;
		case DZ:Alpha3.DZA;
		case AS:Alpha3.ASM;
		case AD:Alpha3.AND;
		case AO:Alpha3.AGO;
		case AI:Alpha3.AIA;
		case AQ:Alpha3.ATA;
		case AG:Alpha3.ATG;
		case AR:Alpha3.ARG;
		case AM:Alpha3.ARM;
		case AW:Alpha3.ABW;
		case AU:Alpha3.AUS;
		case AT:Alpha3.AUT;
		case AZ:Alpha3.AZE;
		case BS:Alpha3.BHS;
		case BH:Alpha3.BHR;
		case BD:Alpha3.BGD;
		case BB:Alpha3.BRB;
		case BY:Alpha3.BLR;
		case BE:Alpha3.BEL;
		case BZ:Alpha3.BLZ;
		case BJ:Alpha3.BEN;
		case BM:Alpha3.BMU;
		case BT:Alpha3.BTN;
		case BO:Alpha3.BOL;
		case BA:Alpha3.BIH;
		case BW:Alpha3.BWA;
		case BV:Alpha3.BVT;
		case BR:Alpha3.BRA;
		case IO:Alpha3.IOT;
		case BN:Alpha3.BRN;
		case BG:Alpha3.BGR;
		case BF:Alpha3.BFA;
		case BI:Alpha3.BDI;
		case KH:Alpha3.KHM;
		case CM:Alpha3.CMR;
		case CA:Alpha3.CAN;
		case CV:Alpha3.CPV;
		case KY:Alpha3.CYM;
		case CF:Alpha3.CAF;
		case TD:Alpha3.TCD;
		case CL:Alpha3.CHL;
		case CN:Alpha3.CHN;
		case CX:Alpha3.CXR;
		case CC:Alpha3.CCK;
		case CO:Alpha3.COL;
		case KM:Alpha3.COM;
		case CG:Alpha3.COG;
		case CD:Alpha3.COD;
		case CK:Alpha3.COK;
		case CR:Alpha3.CRI;
		case CI:Alpha3.CIV;
		case HR:Alpha3.HRV;
		case CU:Alpha3.CUB;
		case CY:Alpha3.CYP;
		case CZ:Alpha3.CZE;
		case DK:Alpha3.DNK;
		case DJ:Alpha3.DJI;
		case DM:Alpha3.DMA;
		case DO:Alpha3.DOM;
		case EC:Alpha3.ECU;
		case EG:Alpha3.EGY;
		case SV:Alpha3.SLV;
		case GQ:Alpha3.GNQ;
		case ER:Alpha3.ERI;
		case EE:Alpha3.EST;
		case ET:Alpha3.ETH;
		case FK:Alpha3.FLK;
		case FO:Alpha3.FRO;
		case FJ:Alpha3.FJI;
		case FI:Alpha3.FIN;
		case FR:Alpha3.FRA;
		case GF:Alpha3.GUF;
		case PF:Alpha3.PYF;
		case TF:Alpha3.ATF;
		case GA:Alpha3.GAB;
		case GM:Alpha3.GMB;
		case GE:Alpha3.GEO;
		case DE:Alpha3.DEU;
		case GH:Alpha3.GHA;
		case GI:Alpha3.GIB;
		case GR:Alpha3.GRC;
		case GL:Alpha3.GRL;
		case GD:Alpha3.GRD;
		case GP:Alpha3.GLP;
		case GU:Alpha3.GUM;
		case GT:Alpha3.GTM;
		case GG:Alpha3.GGY;
		case GN:Alpha3.GIN;
		case GW:Alpha3.GNB;
		case GY:Alpha3.GUY;
		case HT:Alpha3.HTI;
		case HM:Alpha3.HMD;
		case VA:Alpha3.VAT;
		case HN:Alpha3.HND;
		case HK:Alpha3.HKG;
		case HU:Alpha3.HUN;
		case IS:Alpha3.ISL;
		case IN:Alpha3.IND;
		case ID:Alpha3.IDN;
		case IR:Alpha3.IRN;
		case IQ:Alpha3.IRQ;
		case IE:Alpha3.IRL;
		case IM:Alpha3.IMN;
		case IL:Alpha3.ISR;
		case IT:Alpha3.ITA;
		case JM:Alpha3.JAM;
		case JP:Alpha3.JPN;
		case JE:Alpha3.JEY;
		case JO:Alpha3.JOR;
		case KZ:Alpha3.KAZ;
		case KE:Alpha3.KEN;
		case KI:Alpha3.KIR;
		case KP:Alpha3.PRK;
		case KR:Alpha3.KOR;
		case KW:Alpha3.KWT;
		case KG:Alpha3.KGZ;
		case LA:Alpha3.LAO;
		case LV:Alpha3.LVA;
		case LB:Alpha3.LBN;
		case LS:Alpha3.LSO;
		case LR:Alpha3.LBR;
		case LY:Alpha3.LBY;
		case LI:Alpha3.LIE;
		case LT:Alpha3.LTU;
		case LU:Alpha3.LUX;
		case MO:Alpha3.MAC;
		case MK:Alpha3.MKD;
		case MG:Alpha3.MDG;
		case MW:Alpha3.MWI;
		case MY:Alpha3.MYS;
		case MV:Alpha3.MDV;
		case ML:Alpha3.MLI;
		case MT:Alpha3.MLT;
		case MH:Alpha3.MHL;
		case MQ:Alpha3.MTQ;
		case MR:Alpha3.MRT;
		case MU:Alpha3.MUS;
		case YT:Alpha3.MYT;
		case MX:Alpha3.MEX;
		case FM:Alpha3.FSM;
		case MD:Alpha3.MDA;
		case MC:Alpha3.MCO;
		case MN:Alpha3.MNG;
		case ME:Alpha3.MNE;
		case MS:Alpha3.MSR;
		case MA:Alpha3.MAR;
		case MZ:Alpha3.MOZ;
		case MM:Alpha3.MMR;
		case NA:Alpha3.NAM;
		case NR:Alpha3.NRU;
		case NP:Alpha3.NPL;
		case NL:Alpha3.NLD;
		case AN:Alpha3.ANT;
		case NC:Alpha3.NCL;
		case NZ:Alpha3.NZL;
		case NI:Alpha3.NIC;
		case NE:Alpha3.NER;
		case NG:Alpha3.NGA;
		case NU:Alpha3.NIU;
		case NF:Alpha3.NFK;
		case MP:Alpha3.MNP;
		case NO:Alpha3.NOR;
		case OM:Alpha3.OMN;
		case PK:Alpha3.PAK;
		case PW:Alpha3.PLW;
		case PS:Alpha3.PSE;
		case PA:Alpha3.PAN;
		case PG:Alpha3.PNG;
		case PY:Alpha3.PRY;
		case PE:Alpha3.PER;
		case PH:Alpha3.PHL;
		case PN:Alpha3.PCN;
		case PL:Alpha3.POL;
		case PT:Alpha3.PRT;
		case PR:Alpha3.PRI;
		case QA:Alpha3.QAT;
		case RE:Alpha3.REU;
		case RO:Alpha3.ROU;
		case RU:Alpha3.RUS;
		case RW:Alpha3.RWA;
		case SH:Alpha3.SHN;
		case KN:Alpha3.KNA;
		case LC:Alpha3.LCA;
		case PM:Alpha3.SPM;
		case VC:Alpha3.VCT;
		case WS:Alpha3.WSM;
		case SM:Alpha3.SMR;
		case ST:Alpha3.STP;
		case SA:Alpha3.SAU;
		case SN:Alpha3.SEN;
		case RS:Alpha3.SRB;
		case SC:Alpha3.SYC;
		case SL:Alpha3.SLE;
		case SG:Alpha3.SGP;
		case SK:Alpha3.SVK;
		case SI:Alpha3.SVN;
		case SB:Alpha3.SLB;
		case SO:Alpha3.SOM;
		case ZA:Alpha3.ZAF;
		case GS:Alpha3.SGS;
		case SS:Alpha3.SSD;
		case ES:Alpha3.ESP;
		case LK:Alpha3.LKA;
		case SD:Alpha3.SDN;
		case SR:Alpha3.SUR;
		case SJ:Alpha3.SJM;
		case SZ:Alpha3.SWZ;
		case SE:Alpha3.SWE;
		case CH:Alpha3.CHE;
		case SY:Alpha3.SYR;
		case TW:Alpha3.TWN;
		case TJ:Alpha3.TJK;
		case TZ:Alpha3.TZA;
		case TH:Alpha3.THA;
		case TL:Alpha3.TLS;
		case TG:Alpha3.TGO;
		case TK:Alpha3.TKL;
		case TO:Alpha3.TON;
		case TT:Alpha3.TTO;
		case TN:Alpha3.TUN;
		case TR:Alpha3.TUR;
		case TM:Alpha3.TKM;
		case TC:Alpha3.TCA;
		case TV:Alpha3.TUV;
		case UG:Alpha3.UGA;
		case UA:Alpha3.UKR;
		case AE:Alpha3.ARE;
		case GB:Alpha3.GBR;
		case US:Alpha3.USA;
		case UM:Alpha3.UMI;
		case UY:Alpha3.URY;
		case UZ:Alpha3.UZB;
		case VU:Alpha3.VUT;
		case VE:Alpha3.VEN;
		case VN:Alpha3.VNM;
		case VG:Alpha3.VGB;
		case VI:Alpha3.VIR;
		case WF:Alpha3.WLF;
		case EH:Alpha3.ESH;
		case YE:Alpha3.YEM;
		case ZM:Alpha3.ZMB;
		case ZW:Alpha3.ZWE;
	};
	@:to
	public function toNumeric():Numeric return switch ((cast this : Alpha2)) {
		case AF:Numeric.AFG;
		case AL:Numeric.ALB;
		case DZ:Numeric.DZA;
		case AS:Numeric.ASM;
		case AD:Numeric.AND;
		case AO:Numeric.AGO;
		case AI:Numeric.AIA;
		case AQ:Numeric.ATA;
		case AG:Numeric.ATG;
		case AR:Numeric.ARG;
		case AM:Numeric.ARM;
		case AW:Numeric.ABW;
		case AU:Numeric.AUS;
		case AT:Numeric.AUT;
		case AZ:Numeric.AZE;
		case BS:Numeric.BHS;
		case BH:Numeric.BHR;
		case BD:Numeric.BGD;
		case BB:Numeric.BRB;
		case BY:Numeric.BLR;
		case BE:Numeric.BEL;
		case BZ:Numeric.BLZ;
		case BJ:Numeric.BEN;
		case BM:Numeric.BMU;
		case BT:Numeric.BTN;
		case BO:Numeric.BOL;
		case BA:Numeric.BIH;
		case BW:Numeric.BWA;
		case BV:Numeric.BVT;
		case BR:Numeric.BRA;
		case IO:Numeric.IOT;
		case BN:Numeric.BRN;
		case BG:Numeric.BGR;
		case BF:Numeric.BFA;
		case BI:Numeric.BDI;
		case KH:Numeric.KHM;
		case CM:Numeric.CMR;
		case CA:Numeric.CAN;
		case CV:Numeric.CPV;
		case KY:Numeric.CYM;
		case CF:Numeric.CAF;
		case TD:Numeric.TCD;
		case CL:Numeric.CHL;
		case CN:Numeric.CHN;
		case CX:Numeric.CXR;
		case CC:Numeric.CCK;
		case CO:Numeric.COL;
		case KM:Numeric.COM;
		case CG:Numeric.COG;
		case CD:Numeric.COD;
		case CK:Numeric.COK;
		case CR:Numeric.CRI;
		case CI:Numeric.CIV;
		case HR:Numeric.HRV;
		case CU:Numeric.CUB;
		case CY:Numeric.CYP;
		case CZ:Numeric.CZE;
		case DK:Numeric.DNK;
		case DJ:Numeric.DJI;
		case DM:Numeric.DMA;
		case DO:Numeric.DOM;
		case EC:Numeric.ECU;
		case EG:Numeric.EGY;
		case SV:Numeric.SLV;
		case GQ:Numeric.GNQ;
		case ER:Numeric.ERI;
		case EE:Numeric.EST;
		case ET:Numeric.ETH;
		case FK:Numeric.FLK;
		case FO:Numeric.FRO;
		case FJ:Numeric.FJI;
		case FI:Numeric.FIN;
		case FR:Numeric.FRA;
		case GF:Numeric.GUF;
		case PF:Numeric.PYF;
		case TF:Numeric.ATF;
		case GA:Numeric.GAB;
		case GM:Numeric.GMB;
		case GE:Numeric.GEO;
		case DE:Numeric.DEU;
		case GH:Numeric.GHA;
		case GI:Numeric.GIB;
		case GR:Numeric.GRC;
		case GL:Numeric.GRL;
		case GD:Numeric.GRD;
		case GP:Numeric.GLP;
		case GU:Numeric.GUM;
		case GT:Numeric.GTM;
		case GG:Numeric.GGY;
		case GN:Numeric.GIN;
		case GW:Numeric.GNB;
		case GY:Numeric.GUY;
		case HT:Numeric.HTI;
		case HM:Numeric.HMD;
		case VA:Numeric.VAT;
		case HN:Numeric.HND;
		case HK:Numeric.HKG;
		case HU:Numeric.HUN;
		case IS:Numeric.ISL;
		case IN:Numeric.IND;
		case ID:Numeric.IDN;
		case IR:Numeric.IRN;
		case IQ:Numeric.IRQ;
		case IE:Numeric.IRL;
		case IM:Numeric.IMN;
		case IL:Numeric.ISR;
		case IT:Numeric.ITA;
		case JM:Numeric.JAM;
		case JP:Numeric.JPN;
		case JE:Numeric.JEY;
		case JO:Numeric.JOR;
		case KZ:Numeric.KAZ;
		case KE:Numeric.KEN;
		case KI:Numeric.KIR;
		case KP:Numeric.PRK;
		case KR:Numeric.KOR;
		case KW:Numeric.KWT;
		case KG:Numeric.KGZ;
		case LA:Numeric.LAO;
		case LV:Numeric.LVA;
		case LB:Numeric.LBN;
		case LS:Numeric.LSO;
		case LR:Numeric.LBR;
		case LY:Numeric.LBY;
		case LI:Numeric.LIE;
		case LT:Numeric.LTU;
		case LU:Numeric.LUX;
		case MO:Numeric.MAC;
		case MK:Numeric.MKD;
		case MG:Numeric.MDG;
		case MW:Numeric.MWI;
		case MY:Numeric.MYS;
		case MV:Numeric.MDV;
		case ML:Numeric.MLI;
		case MT:Numeric.MLT;
		case MH:Numeric.MHL;
		case MQ:Numeric.MTQ;
		case MR:Numeric.MRT;
		case MU:Numeric.MUS;
		case YT:Numeric.MYT;
		case MX:Numeric.MEX;
		case FM:Numeric.FSM;
		case MD:Numeric.MDA;
		case MC:Numeric.MCO;
		case MN:Numeric.MNG;
		case ME:Numeric.MNE;
		case MS:Numeric.MSR;
		case MA:Numeric.MAR;
		case MZ:Numeric.MOZ;
		case MM:Numeric.MMR;
		case NA:Numeric.NAM;
		case NR:Numeric.NRU;
		case NP:Numeric.NPL;
		case NL:Numeric.NLD;
		case AN:Numeric.ANT;
		case NC:Numeric.NCL;
		case NZ:Numeric.NZL;
		case NI:Numeric.NIC;
		case NE:Numeric.NER;
		case NG:Numeric.NGA;
		case NU:Numeric.NIU;
		case NF:Numeric.NFK;
		case MP:Numeric.MNP;
		case NO:Numeric.NOR;
		case OM:Numeric.OMN;
		case PK:Numeric.PAK;
		case PW:Numeric.PLW;
		case PS:Numeric.PSE;
		case PA:Numeric.PAN;
		case PG:Numeric.PNG;
		case PY:Numeric.PRY;
		case PE:Numeric.PER;
		case PH:Numeric.PHL;
		case PN:Numeric.PCN;
		case PL:Numeric.POL;
		case PT:Numeric.PRT;
		case PR:Numeric.PRI;
		case QA:Numeric.QAT;
		case RE:Numeric.REU;
		case RO:Numeric.ROU;
		case RU:Numeric.RUS;
		case RW:Numeric.RWA;
		case SH:Numeric.SHN;
		case KN:Numeric.KNA;
		case LC:Numeric.LCA;
		case PM:Numeric.SPM;
		case VC:Numeric.VCT;
		case WS:Numeric.WSM;
		case SM:Numeric.SMR;
		case ST:Numeric.STP;
		case SA:Numeric.SAU;
		case SN:Numeric.SEN;
		case RS:Numeric.SRB;
		case SC:Numeric.SYC;
		case SL:Numeric.SLE;
		case SG:Numeric.SGP;
		case SK:Numeric.SVK;
		case SI:Numeric.SVN;
		case SB:Numeric.SLB;
		case SO:Numeric.SOM;
		case ZA:Numeric.ZAF;
		case GS:Numeric.SGS;
		case SS:Numeric.SSD;
		case ES:Numeric.ESP;
		case LK:Numeric.LKA;
		case SD:Numeric.SDN;
		case SR:Numeric.SUR;
		case SJ:Numeric.SJM;
		case SZ:Numeric.SWZ;
		case SE:Numeric.SWE;
		case CH:Numeric.CHE;
		case SY:Numeric.SYR;
		case TW:Numeric.TWN;
		case TJ:Numeric.TJK;
		case TZ:Numeric.TZA;
		case TH:Numeric.THA;
		case TL:Numeric.TLS;
		case TG:Numeric.TGO;
		case TK:Numeric.TKL;
		case TO:Numeric.TON;
		case TT:Numeric.TTO;
		case TN:Numeric.TUN;
		case TR:Numeric.TUR;
		case TM:Numeric.TKM;
		case TC:Numeric.TCA;
		case TV:Numeric.TUV;
		case UG:Numeric.UGA;
		case UA:Numeric.UKR;
		case AE:Numeric.ARE;
		case GB:Numeric.GBR;
		case US:Numeric.USA;
		case UM:Numeric.UMI;
		case UY:Numeric.URY;
		case UZ:Numeric.UZB;
		case VU:Numeric.VUT;
		case VE:Numeric.VEN;
		case VN:Numeric.VNM;
		case VG:Numeric.VGB;
		case VI:Numeric.VIR;
		case WF:Numeric.WLF;
		case EH:Numeric.ESH;
		case YE:Numeric.YEM;
		case ZM:Numeric.ZMB;
		case ZW:Numeric.ZWE;
	};
	var AF = "AF";
	var AL = "AL";
	var DZ = "DZ";
	var AS = "AS";
	var AD = "AD";
	var AO = "AO";
	var AI = "AI";
	var AQ = "AQ";
	var AG = "AG";
	var AR = "AR";
	var AM = "AM";
	var AW = "AW";
	var AU = "AU";
	var AT = "AT";
	var AZ = "AZ";
	var BS = "BS";
	var BH = "BH";
	var BD = "BD";
	var BB = "BB";
	var BY = "BY";
	var BE = "BE";
	var BZ = "BZ";
	var BJ = "BJ";
	var BM = "BM";
	var BT = "BT";
	var BO = "BO";
	var BA = "BA";
	var BW = "BW";
	var BV = "BV";
	var BR = "BR";
	var IO = "IO";
	var BN = "BN";
	var BG = "BG";
	var BF = "BF";
	var BI = "BI";
	var KH = "KH";
	var CM = "CM";
	var CA = "CA";
	var CV = "CV";
	var KY = "KY";
	var CF = "CF";
	var TD = "TD";
	var CL = "CL";
	var CN = "CN";
	var CX = "CX";
	var CC = "CC";
	var CO = "CO";
	var KM = "KM";
	var CG = "CG";
	var CD = "CD";
	var CK = "CK";
	var CR = "CR";
	var CI = "CI";
	var HR = "HR";
	var CU = "CU";
	var CY = "CY";
	var CZ = "CZ";
	var DK = "DK";
	var DJ = "DJ";
	var DM = "DM";
	var DO = "DO";
	var EC = "EC";
	var EG = "EG";
	var SV = "SV";
	var GQ = "GQ";
	var ER = "ER";
	var EE = "EE";
	var ET = "ET";
	var FK = "FK";
	var FO = "FO";
	var FJ = "FJ";
	var FI = "FI";
	var FR = "FR";
	var GF = "GF";
	var PF = "PF";
	var TF = "TF";
	var GA = "GA";
	var GM = "GM";
	var GE = "GE";
	var DE = "DE";
	var GH = "GH";
	var GI = "GI";
	var GR = "GR";
	var GL = "GL";
	var GD = "GD";
	var GP = "GP";
	var GU = "GU";
	var GT = "GT";
	var GG = "GG";
	var GN = "GN";
	var GW = "GW";
	var GY = "GY";
	var HT = "HT";
	var HM = "HM";
	var VA = "VA";
	var HN = "HN";
	var HK = "HK";
	var HU = "HU";
	var IS = "IS";
	var IN = "IN";
	var ID = "ID";
	var IR = "IR";
	var IQ = "IQ";
	var IE = "IE";
	var IM = "IM";
	var IL = "IL";
	var IT = "IT";
	var JM = "JM";
	var JP = "JP";
	var JE = "JE";
	var JO = "JO";
	var KZ = "KZ";
	var KE = "KE";
	var KI = "KI";
	var KP = "KP";
	var KR = "KR";
	var KW = "KW";
	var KG = "KG";
	var LA = "LA";
	var LV = "LV";
	var LB = "LB";
	var LS = "LS";
	var LR = "LR";
	var LY = "LY";
	var LI = "LI";
	var LT = "LT";
	var LU = "LU";
	var MO = "MO";
	var MK = "MK";
	var MG = "MG";
	var MW = "MW";
	var MY = "MY";
	var MV = "MV";
	var ML = "ML";
	var MT = "MT";
	var MH = "MH";
	var MQ = "MQ";
	var MR = "MR";
	var MU = "MU";
	var YT = "YT";
	var MX = "MX";
	var FM = "FM";
	var MD = "MD";
	var MC = "MC";
	var MN = "MN";
	var ME = "ME";
	var MS = "MS";
	var MA = "MA";
	var MZ = "MZ";
	var MM = "MM";
	var NA = "NA";
	var NR = "NR";
	var NP = "NP";
	var NL = "NL";
	var AN = "AN";
	var NC = "NC";
	var NZ = "NZ";
	var NI = "NI";
	var NE = "NE";
	var NG = "NG";
	var NU = "NU";
	var NF = "NF";
	var MP = "MP";
	var NO = "NO";
	var OM = "OM";
	var PK = "PK";
	var PW = "PW";
	var PS = "PS";
	var PA = "PA";
	var PG = "PG";
	var PY = "PY";
	var PE = "PE";
	var PH = "PH";
	var PN = "PN";
	var PL = "PL";
	var PT = "PT";
	var PR = "PR";
	var QA = "QA";
	var RE = "RE";
	var RO = "RO";
	var RU = "RU";
	var RW = "RW";
	var SH = "SH";
	var KN = "KN";
	var LC = "LC";
	var PM = "PM";
	var VC = "VC";
	var WS = "WS";
	var SM = "SM";
	var ST = "ST";
	var SA = "SA";
	var SN = "SN";
	var RS = "RS";
	var SC = "SC";
	var SL = "SL";
	var SG = "SG";
	var SK = "SK";
	var SI = "SI";
	var SB = "SB";
	var SO = "SO";
	var ZA = "ZA";
	var GS = "GS";
	var SS = "SS";
	var ES = "ES";
	var LK = "LK";
	var SD = "SD";
	var SR = "SR";
	var SJ = "SJ";
	var SZ = "SZ";
	var SE = "SE";
	var CH = "CH";
	var SY = "SY";
	var TW = "TW";
	var TJ = "TJ";
	var TZ = "TZ";
	var TH = "TH";
	var TL = "TL";
	var TG = "TG";
	var TK = "TK";
	var TO = "TO";
	var TT = "TT";
	var TN = "TN";
	var TR = "TR";
	var TM = "TM";
	var TC = "TC";
	var TV = "TV";
	var UG = "UG";
	var UA = "UA";
	var AE = "AE";
	var GB = "GB";
	var US = "US";
	var UM = "UM";
	var UY = "UY";
	var UZ = "UZ";
	var VU = "VU";
	var VE = "VE";
	var VN = "VN";
	var VG = "VG";
	var VI = "VI";
	var WF = "WF";
	var EH = "EH";
	var YE = "YE";
	var ZM = "ZM";
	var ZW = "ZW";
}