package iso3166.part1;
@:enum abstract Alpha3(String) to String {
	@:to
	public function toAlpha2():Alpha2 return switch ((cast this : Alpha3)) {
		case AFG:Alpha2.AF;
		case ALB:Alpha2.AL;
		case DZA:Alpha2.DZ;
		case ASM:Alpha2.AS;
		case AND:Alpha2.AD;
		case AGO:Alpha2.AO;
		case AIA:Alpha2.AI;
		case ATA:Alpha2.AQ;
		case ATG:Alpha2.AG;
		case ARG:Alpha2.AR;
		case ARM:Alpha2.AM;
		case ABW:Alpha2.AW;
		case AUS:Alpha2.AU;
		case AUT:Alpha2.AT;
		case AZE:Alpha2.AZ;
		case BHS:Alpha2.BS;
		case BHR:Alpha2.BH;
		case BGD:Alpha2.BD;
		case BRB:Alpha2.BB;
		case BLR:Alpha2.BY;
		case BEL:Alpha2.BE;
		case BLZ:Alpha2.BZ;
		case BEN:Alpha2.BJ;
		case BMU:Alpha2.BM;
		case BTN:Alpha2.BT;
		case BOL:Alpha2.BO;
		case BIH:Alpha2.BA;
		case BWA:Alpha2.BW;
		case BVT:Alpha2.BV;
		case BRA:Alpha2.BR;
		case IOT:Alpha2.IO;
		case BRN:Alpha2.BN;
		case BGR:Alpha2.BG;
		case BFA:Alpha2.BF;
		case BDI:Alpha2.BI;
		case KHM:Alpha2.KH;
		case CMR:Alpha2.CM;
		case CAN:Alpha2.CA;
		case CPV:Alpha2.CV;
		case CYM:Alpha2.KY;
		case CAF:Alpha2.CF;
		case TCD:Alpha2.TD;
		case CHL:Alpha2.CL;
		case CHN:Alpha2.CN;
		case CXR:Alpha2.CX;
		case CCK:Alpha2.CC;
		case COL:Alpha2.CO;
		case COM:Alpha2.KM;
		case COG:Alpha2.CG;
		case COD:Alpha2.CD;
		case COK:Alpha2.CK;
		case CRI:Alpha2.CR;
		case CIV:Alpha2.CI;
		case HRV:Alpha2.HR;
		case CUB:Alpha2.CU;
		case CYP:Alpha2.CY;
		case CZE:Alpha2.CZ;
		case DNK:Alpha2.DK;
		case DJI:Alpha2.DJ;
		case DMA:Alpha2.DM;
		case DOM:Alpha2.DO;
		case ECU:Alpha2.EC;
		case EGY:Alpha2.EG;
		case SLV:Alpha2.SV;
		case GNQ:Alpha2.GQ;
		case ERI:Alpha2.ER;
		case EST:Alpha2.EE;
		case ETH:Alpha2.ET;
		case FLK:Alpha2.FK;
		case FRO:Alpha2.FO;
		case FJI:Alpha2.FJ;
		case FIN:Alpha2.FI;
		case FRA:Alpha2.FR;
		case GUF:Alpha2.GF;
		case PYF:Alpha2.PF;
		case ATF:Alpha2.TF;
		case GAB:Alpha2.GA;
		case GMB:Alpha2.GM;
		case GEO:Alpha2.GE;
		case DEU:Alpha2.DE;
		case GHA:Alpha2.GH;
		case GIB:Alpha2.GI;
		case GRC:Alpha2.GR;
		case GRL:Alpha2.GL;
		case GRD:Alpha2.GD;
		case GLP:Alpha2.GP;
		case GUM:Alpha2.GU;
		case GTM:Alpha2.GT;
		case GGY:Alpha2.GG;
		case GIN:Alpha2.GN;
		case GNB:Alpha2.GW;
		case GUY:Alpha2.GY;
		case HTI:Alpha2.HT;
		case HMD:Alpha2.HM;
		case VAT:Alpha2.VA;
		case HND:Alpha2.HN;
		case HKG:Alpha2.HK;
		case HUN:Alpha2.HU;
		case ISL:Alpha2.IS;
		case IND:Alpha2.IN;
		case IDN:Alpha2.ID;
		case IRN:Alpha2.IR;
		case IRQ:Alpha2.IQ;
		case IRL:Alpha2.IE;
		case IMN:Alpha2.IM;
		case ISR:Alpha2.IL;
		case ITA:Alpha2.IT;
		case JAM:Alpha2.JM;
		case JPN:Alpha2.JP;
		case JEY:Alpha2.JE;
		case JOR:Alpha2.JO;
		case KAZ:Alpha2.KZ;
		case KEN:Alpha2.KE;
		case KIR:Alpha2.KI;
		case PRK:Alpha2.KP;
		case KOR:Alpha2.KR;
		case KWT:Alpha2.KW;
		case KGZ:Alpha2.KG;
		case LAO:Alpha2.LA;
		case LVA:Alpha2.LV;
		case LBN:Alpha2.LB;
		case LSO:Alpha2.LS;
		case LBR:Alpha2.LR;
		case LBY:Alpha2.LY;
		case LIE:Alpha2.LI;
		case LTU:Alpha2.LT;
		case LUX:Alpha2.LU;
		case MAC:Alpha2.MO;
		case MKD:Alpha2.MK;
		case MDG:Alpha2.MG;
		case MWI:Alpha2.MW;
		case MYS:Alpha2.MY;
		case MDV:Alpha2.MV;
		case MLI:Alpha2.ML;
		case MLT:Alpha2.MT;
		case MHL:Alpha2.MH;
		case MTQ:Alpha2.MQ;
		case MRT:Alpha2.MR;
		case MUS:Alpha2.MU;
		case MYT:Alpha2.YT;
		case MEX:Alpha2.MX;
		case FSM:Alpha2.FM;
		case MDA:Alpha2.MD;
		case MCO:Alpha2.MC;
		case MNG:Alpha2.MN;
		case MNE:Alpha2.ME;
		case MSR:Alpha2.MS;
		case MAR:Alpha2.MA;
		case MOZ:Alpha2.MZ;
		case MMR:Alpha2.MM;
		case NAM:Alpha2.NA;
		case NRU:Alpha2.NR;
		case NPL:Alpha2.NP;
		case NLD:Alpha2.NL;
		case ANT:Alpha2.AN;
		case NCL:Alpha2.NC;
		case NZL:Alpha2.NZ;
		case NIC:Alpha2.NI;
		case NER:Alpha2.NE;
		case NGA:Alpha2.NG;
		case NIU:Alpha2.NU;
		case NFK:Alpha2.NF;
		case MNP:Alpha2.MP;
		case NOR:Alpha2.NO;
		case OMN:Alpha2.OM;
		case PAK:Alpha2.PK;
		case PLW:Alpha2.PW;
		case PSE:Alpha2.PS;
		case PAN:Alpha2.PA;
		case PNG:Alpha2.PG;
		case PRY:Alpha2.PY;
		case PER:Alpha2.PE;
		case PHL:Alpha2.PH;
		case PCN:Alpha2.PN;
		case POL:Alpha2.PL;
		case PRT:Alpha2.PT;
		case PRI:Alpha2.PR;
		case QAT:Alpha2.QA;
		case REU:Alpha2.RE;
		case ROU:Alpha2.RO;
		case RUS:Alpha2.RU;
		case RWA:Alpha2.RW;
		case SHN:Alpha2.SH;
		case KNA:Alpha2.KN;
		case LCA:Alpha2.LC;
		case SPM:Alpha2.PM;
		case VCT:Alpha2.VC;
		case WSM:Alpha2.WS;
		case SMR:Alpha2.SM;
		case STP:Alpha2.ST;
		case SAU:Alpha2.SA;
		case SEN:Alpha2.SN;
		case SRB:Alpha2.RS;
		case SYC:Alpha2.SC;
		case SLE:Alpha2.SL;
		case SGP:Alpha2.SG;
		case SVK:Alpha2.SK;
		case SVN:Alpha2.SI;
		case SLB:Alpha2.SB;
		case SOM:Alpha2.SO;
		case ZAF:Alpha2.ZA;
		case SGS:Alpha2.GS;
		case SSD:Alpha2.SS;
		case ESP:Alpha2.ES;
		case LKA:Alpha2.LK;
		case SDN:Alpha2.SD;
		case SUR:Alpha2.SR;
		case SJM:Alpha2.SJ;
		case SWZ:Alpha2.SZ;
		case SWE:Alpha2.SE;
		case CHE:Alpha2.CH;
		case SYR:Alpha2.SY;
		case TWN:Alpha2.TW;
		case TJK:Alpha2.TJ;
		case TZA:Alpha2.TZ;
		case THA:Alpha2.TH;
		case TLS:Alpha2.TL;
		case TGO:Alpha2.TG;
		case TKL:Alpha2.TK;
		case TON:Alpha2.TO;
		case TTO:Alpha2.TT;
		case TUN:Alpha2.TN;
		case TUR:Alpha2.TR;
		case TKM:Alpha2.TM;
		case TCA:Alpha2.TC;
		case TUV:Alpha2.TV;
		case UGA:Alpha2.UG;
		case UKR:Alpha2.UA;
		case ARE:Alpha2.AE;
		case GBR:Alpha2.GB;
		case USA:Alpha2.US;
		case UMI:Alpha2.UM;
		case URY:Alpha2.UY;
		case UZB:Alpha2.UZ;
		case VUT:Alpha2.VU;
		case VEN:Alpha2.VE;
		case VNM:Alpha2.VN;
		case VGB:Alpha2.VG;
		case VIR:Alpha2.VI;
		case WLF:Alpha2.WF;
		case ESH:Alpha2.EH;
		case YEM:Alpha2.YE;
		case ZMB:Alpha2.ZM;
		case ZWE:Alpha2.ZW;
	};
	@:to
	public function toNumeric():Numeric return switch ((cast this : Alpha3)) {
		case AFG:Numeric.AFG;
		case ALB:Numeric.ALB;
		case DZA:Numeric.DZA;
		case ASM:Numeric.ASM;
		case AND:Numeric.AND;
		case AGO:Numeric.AGO;
		case AIA:Numeric.AIA;
		case ATA:Numeric.ATA;
		case ATG:Numeric.ATG;
		case ARG:Numeric.ARG;
		case ARM:Numeric.ARM;
		case ABW:Numeric.ABW;
		case AUS:Numeric.AUS;
		case AUT:Numeric.AUT;
		case AZE:Numeric.AZE;
		case BHS:Numeric.BHS;
		case BHR:Numeric.BHR;
		case BGD:Numeric.BGD;
		case BRB:Numeric.BRB;
		case BLR:Numeric.BLR;
		case BEL:Numeric.BEL;
		case BLZ:Numeric.BLZ;
		case BEN:Numeric.BEN;
		case BMU:Numeric.BMU;
		case BTN:Numeric.BTN;
		case BOL:Numeric.BOL;
		case BIH:Numeric.BIH;
		case BWA:Numeric.BWA;
		case BVT:Numeric.BVT;
		case BRA:Numeric.BRA;
		case IOT:Numeric.IOT;
		case BRN:Numeric.BRN;
		case BGR:Numeric.BGR;
		case BFA:Numeric.BFA;
		case BDI:Numeric.BDI;
		case KHM:Numeric.KHM;
		case CMR:Numeric.CMR;
		case CAN:Numeric.CAN;
		case CPV:Numeric.CPV;
		case CYM:Numeric.CYM;
		case CAF:Numeric.CAF;
		case TCD:Numeric.TCD;
		case CHL:Numeric.CHL;
		case CHN:Numeric.CHN;
		case CXR:Numeric.CXR;
		case CCK:Numeric.CCK;
		case COL:Numeric.COL;
		case COM:Numeric.COM;
		case COG:Numeric.COG;
		case COD:Numeric.COD;
		case COK:Numeric.COK;
		case CRI:Numeric.CRI;
		case CIV:Numeric.CIV;
		case HRV:Numeric.HRV;
		case CUB:Numeric.CUB;
		case CYP:Numeric.CYP;
		case CZE:Numeric.CZE;
		case DNK:Numeric.DNK;
		case DJI:Numeric.DJI;
		case DMA:Numeric.DMA;
		case DOM:Numeric.DOM;
		case ECU:Numeric.ECU;
		case EGY:Numeric.EGY;
		case SLV:Numeric.SLV;
		case GNQ:Numeric.GNQ;
		case ERI:Numeric.ERI;
		case EST:Numeric.EST;
		case ETH:Numeric.ETH;
		case FLK:Numeric.FLK;
		case FRO:Numeric.FRO;
		case FJI:Numeric.FJI;
		case FIN:Numeric.FIN;
		case FRA:Numeric.FRA;
		case GUF:Numeric.GUF;
		case PYF:Numeric.PYF;
		case ATF:Numeric.ATF;
		case GAB:Numeric.GAB;
		case GMB:Numeric.GMB;
		case GEO:Numeric.GEO;
		case DEU:Numeric.DEU;
		case GHA:Numeric.GHA;
		case GIB:Numeric.GIB;
		case GRC:Numeric.GRC;
		case GRL:Numeric.GRL;
		case GRD:Numeric.GRD;
		case GLP:Numeric.GLP;
		case GUM:Numeric.GUM;
		case GTM:Numeric.GTM;
		case GGY:Numeric.GGY;
		case GIN:Numeric.GIN;
		case GNB:Numeric.GNB;
		case GUY:Numeric.GUY;
		case HTI:Numeric.HTI;
		case HMD:Numeric.HMD;
		case VAT:Numeric.VAT;
		case HND:Numeric.HND;
		case HKG:Numeric.HKG;
		case HUN:Numeric.HUN;
		case ISL:Numeric.ISL;
		case IND:Numeric.IND;
		case IDN:Numeric.IDN;
		case IRN:Numeric.IRN;
		case IRQ:Numeric.IRQ;
		case IRL:Numeric.IRL;
		case IMN:Numeric.IMN;
		case ISR:Numeric.ISR;
		case ITA:Numeric.ITA;
		case JAM:Numeric.JAM;
		case JPN:Numeric.JPN;
		case JEY:Numeric.JEY;
		case JOR:Numeric.JOR;
		case KAZ:Numeric.KAZ;
		case KEN:Numeric.KEN;
		case KIR:Numeric.KIR;
		case PRK:Numeric.PRK;
		case KOR:Numeric.KOR;
		case KWT:Numeric.KWT;
		case KGZ:Numeric.KGZ;
		case LAO:Numeric.LAO;
		case LVA:Numeric.LVA;
		case LBN:Numeric.LBN;
		case LSO:Numeric.LSO;
		case LBR:Numeric.LBR;
		case LBY:Numeric.LBY;
		case LIE:Numeric.LIE;
		case LTU:Numeric.LTU;
		case LUX:Numeric.LUX;
		case MAC:Numeric.MAC;
		case MKD:Numeric.MKD;
		case MDG:Numeric.MDG;
		case MWI:Numeric.MWI;
		case MYS:Numeric.MYS;
		case MDV:Numeric.MDV;
		case MLI:Numeric.MLI;
		case MLT:Numeric.MLT;
		case MHL:Numeric.MHL;
		case MTQ:Numeric.MTQ;
		case MRT:Numeric.MRT;
		case MUS:Numeric.MUS;
		case MYT:Numeric.MYT;
		case MEX:Numeric.MEX;
		case FSM:Numeric.FSM;
		case MDA:Numeric.MDA;
		case MCO:Numeric.MCO;
		case MNG:Numeric.MNG;
		case MNE:Numeric.MNE;
		case MSR:Numeric.MSR;
		case MAR:Numeric.MAR;
		case MOZ:Numeric.MOZ;
		case MMR:Numeric.MMR;
		case NAM:Numeric.NAM;
		case NRU:Numeric.NRU;
		case NPL:Numeric.NPL;
		case NLD:Numeric.NLD;
		case ANT:Numeric.ANT;
		case NCL:Numeric.NCL;
		case NZL:Numeric.NZL;
		case NIC:Numeric.NIC;
		case NER:Numeric.NER;
		case NGA:Numeric.NGA;
		case NIU:Numeric.NIU;
		case NFK:Numeric.NFK;
		case MNP:Numeric.MNP;
		case NOR:Numeric.NOR;
		case OMN:Numeric.OMN;
		case PAK:Numeric.PAK;
		case PLW:Numeric.PLW;
		case PSE:Numeric.PSE;
		case PAN:Numeric.PAN;
		case PNG:Numeric.PNG;
		case PRY:Numeric.PRY;
		case PER:Numeric.PER;
		case PHL:Numeric.PHL;
		case PCN:Numeric.PCN;
		case POL:Numeric.POL;
		case PRT:Numeric.PRT;
		case PRI:Numeric.PRI;
		case QAT:Numeric.QAT;
		case REU:Numeric.REU;
		case ROU:Numeric.ROU;
		case RUS:Numeric.RUS;
		case RWA:Numeric.RWA;
		case SHN:Numeric.SHN;
		case KNA:Numeric.KNA;
		case LCA:Numeric.LCA;
		case SPM:Numeric.SPM;
		case VCT:Numeric.VCT;
		case WSM:Numeric.WSM;
		case SMR:Numeric.SMR;
		case STP:Numeric.STP;
		case SAU:Numeric.SAU;
		case SEN:Numeric.SEN;
		case SRB:Numeric.SRB;
		case SYC:Numeric.SYC;
		case SLE:Numeric.SLE;
		case SGP:Numeric.SGP;
		case SVK:Numeric.SVK;
		case SVN:Numeric.SVN;
		case SLB:Numeric.SLB;
		case SOM:Numeric.SOM;
		case ZAF:Numeric.ZAF;
		case SGS:Numeric.SGS;
		case SSD:Numeric.SSD;
		case ESP:Numeric.ESP;
		case LKA:Numeric.LKA;
		case SDN:Numeric.SDN;
		case SUR:Numeric.SUR;
		case SJM:Numeric.SJM;
		case SWZ:Numeric.SWZ;
		case SWE:Numeric.SWE;
		case CHE:Numeric.CHE;
		case SYR:Numeric.SYR;
		case TWN:Numeric.TWN;
		case TJK:Numeric.TJK;
		case TZA:Numeric.TZA;
		case THA:Numeric.THA;
		case TLS:Numeric.TLS;
		case TGO:Numeric.TGO;
		case TKL:Numeric.TKL;
		case TON:Numeric.TON;
		case TTO:Numeric.TTO;
		case TUN:Numeric.TUN;
		case TUR:Numeric.TUR;
		case TKM:Numeric.TKM;
		case TCA:Numeric.TCA;
		case TUV:Numeric.TUV;
		case UGA:Numeric.UGA;
		case UKR:Numeric.UKR;
		case ARE:Numeric.ARE;
		case GBR:Numeric.GBR;
		case USA:Numeric.USA;
		case UMI:Numeric.UMI;
		case URY:Numeric.URY;
		case UZB:Numeric.UZB;
		case VUT:Numeric.VUT;
		case VEN:Numeric.VEN;
		case VNM:Numeric.VNM;
		case VGB:Numeric.VGB;
		case VIR:Numeric.VIR;
		case WLF:Numeric.WLF;
		case ESH:Numeric.ESH;
		case YEM:Numeric.YEM;
		case ZMB:Numeric.ZMB;
		case ZWE:Numeric.ZWE;
	};
	var AFG = "AFG";
	var ALB = "ALB";
	var DZA = "DZA";
	var ASM = "ASM";
	var AND = "AND";
	var AGO = "AGO";
	var AIA = "AIA";
	var ATA = "ATA";
	var ATG = "ATG";
	var ARG = "ARG";
	var ARM = "ARM";
	var ABW = "ABW";
	var AUS = "AUS";
	var AUT = "AUT";
	var AZE = "AZE";
	var BHS = "BHS";
	var BHR = "BHR";
	var BGD = "BGD";
	var BRB = "BRB";
	var BLR = "BLR";
	var BEL = "BEL";
	var BLZ = "BLZ";
	var BEN = "BEN";
	var BMU = "BMU";
	var BTN = "BTN";
	var BOL = "BOL";
	var BIH = "BIH";
	var BWA = "BWA";
	var BVT = "BVT";
	var BRA = "BRA";
	var IOT = "IOT";
	var BRN = "BRN";
	var BGR = "BGR";
	var BFA = "BFA";
	var BDI = "BDI";
	var KHM = "KHM";
	var CMR = "CMR";
	var CAN = "CAN";
	var CPV = "CPV";
	var CYM = "CYM";
	var CAF = "CAF";
	var TCD = "TCD";
	var CHL = "CHL";
	var CHN = "CHN";
	var CXR = "CXR";
	var CCK = "CCK";
	var COL = "COL";
	var COM = "COM";
	var COG = "COG";
	var COD = "COD";
	var COK = "COK";
	var CRI = "CRI";
	var CIV = "CIV";
	var HRV = "HRV";
	var CUB = "CUB";
	var CYP = "CYP";
	var CZE = "CZE";
	var DNK = "DNK";
	var DJI = "DJI";
	var DMA = "DMA";
	var DOM = "DOM";
	var ECU = "ECU";
	var EGY = "EGY";
	var SLV = "SLV";
	var GNQ = "GNQ";
	var ERI = "ERI";
	var EST = "EST";
	var ETH = "ETH";
	var FLK = "FLK";
	var FRO = "FRO";
	var FJI = "FJI";
	var FIN = "FIN";
	var FRA = "FRA";
	var GUF = "GUF";
	var PYF = "PYF";
	var ATF = "ATF";
	var GAB = "GAB";
	var GMB = "GMB";
	var GEO = "GEO";
	var DEU = "DEU";
	var GHA = "GHA";
	var GIB = "GIB";
	var GRC = "GRC";
	var GRL = "GRL";
	var GRD = "GRD";
	var GLP = "GLP";
	var GUM = "GUM";
	var GTM = "GTM";
	var GGY = "GGY";
	var GIN = "GIN";
	var GNB = "GNB";
	var GUY = "GUY";
	var HTI = "HTI";
	var HMD = "HMD";
	var VAT = "VAT";
	var HND = "HND";
	var HKG = "HKG";
	var HUN = "HUN";
	var ISL = "ISL";
	var IND = "IND";
	var IDN = "IDN";
	var IRN = "IRN";
	var IRQ = "IRQ";
	var IRL = "IRL";
	var IMN = "IMN";
	var ISR = "ISR";
	var ITA = "ITA";
	var JAM = "JAM";
	var JPN = "JPN";
	var JEY = "JEY";
	var JOR = "JOR";
	var KAZ = "KAZ";
	var KEN = "KEN";
	var KIR = "KIR";
	var PRK = "PRK";
	var KOR = "KOR";
	var KWT = "KWT";
	var KGZ = "KGZ";
	var LAO = "LAO";
	var LVA = "LVA";
	var LBN = "LBN";
	var LSO = "LSO";
	var LBR = "LBR";
	var LBY = "LBY";
	var LIE = "LIE";
	var LTU = "LTU";
	var LUX = "LUX";
	var MAC = "MAC";
	var MKD = "MKD";
	var MDG = "MDG";
	var MWI = "MWI";
	var MYS = "MYS";
	var MDV = "MDV";
	var MLI = "MLI";
	var MLT = "MLT";
	var MHL = "MHL";
	var MTQ = "MTQ";
	var MRT = "MRT";
	var MUS = "MUS";
	var MYT = "MYT";
	var MEX = "MEX";
	var FSM = "FSM";
	var MDA = "MDA";
	var MCO = "MCO";
	var MNG = "MNG";
	var MNE = "MNE";
	var MSR = "MSR";
	var MAR = "MAR";
	var MOZ = "MOZ";
	var MMR = "MMR";
	var NAM = "NAM";
	var NRU = "NRU";
	var NPL = "NPL";
	var NLD = "NLD";
	var ANT = "ANT";
	var NCL = "NCL";
	var NZL = "NZL";
	var NIC = "NIC";
	var NER = "NER";
	var NGA = "NGA";
	var NIU = "NIU";
	var NFK = "NFK";
	var MNP = "MNP";
	var NOR = "NOR";
	var OMN = "OMN";
	var PAK = "PAK";
	var PLW = "PLW";
	var PSE = "PSE";
	var PAN = "PAN";
	var PNG = "PNG";
	var PRY = "PRY";
	var PER = "PER";
	var PHL = "PHL";
	var PCN = "PCN";
	var POL = "POL";
	var PRT = "PRT";
	var PRI = "PRI";
	var QAT = "QAT";
	var REU = "REU";
	var ROU = "ROU";
	var RUS = "RUS";
	var RWA = "RWA";
	var SHN = "SHN";
	var KNA = "KNA";
	var LCA = "LCA";
	var SPM = "SPM";
	var VCT = "VCT";
	var WSM = "WSM";
	var SMR = "SMR";
	var STP = "STP";
	var SAU = "SAU";
	var SEN = "SEN";
	var SRB = "SRB";
	var SYC = "SYC";
	var SLE = "SLE";
	var SGP = "SGP";
	var SVK = "SVK";
	var SVN = "SVN";
	var SLB = "SLB";
	var SOM = "SOM";
	var ZAF = "ZAF";
	var SGS = "SGS";
	var SSD = "SSD";
	var ESP = "ESP";
	var LKA = "LKA";
	var SDN = "SDN";
	var SUR = "SUR";
	var SJM = "SJM";
	var SWZ = "SWZ";
	var SWE = "SWE";
	var CHE = "CHE";
	var SYR = "SYR";
	var TWN = "TWN";
	var TJK = "TJK";
	var TZA = "TZA";
	var THA = "THA";
	var TLS = "TLS";
	var TGO = "TGO";
	var TKL = "TKL";
	var TON = "TON";
	var TTO = "TTO";
	var TUN = "TUN";
	var TUR = "TUR";
	var TKM = "TKM";
	var TCA = "TCA";
	var TUV = "TUV";
	var UGA = "UGA";
	var UKR = "UKR";
	var ARE = "ARE";
	var GBR = "GBR";
	var USA = "USA";
	var UMI = "UMI";
	var URY = "URY";
	var UZB = "UZB";
	var VUT = "VUT";
	var VEN = "VEN";
	var VNM = "VNM";
	var VGB = "VGB";
	var VIR = "VIR";
	var WLF = "WLF";
	var ESH = "ESH";
	var YEM = "YEM";
	var ZMB = "ZMB";
	var ZWE = "ZWE";
}