package iso3166.part1;
@:enum abstract Numeric(Int) to Int {
	@:to
	public function toAlpha2():Alpha2 return switch ((cast this : Numeric)) {
		case AFG:Alpha2.AF;
		case ALB:Alpha2.AL;
		case DZA:Alpha2.DZ;
		case ASM:Alpha2.AS;
		case AND:Alpha2.AD;
		case AGO:Alpha2.AO;
		case AIA:Alpha2.AI;
		case ATA:Alpha2.AQ;
		case ATG:Alpha2.AG;
		case ARG:Alpha2.AR;
		case ARM:Alpha2.AM;
		case ABW:Alpha2.AW;
		case AUS:Alpha2.AU;
		case AUT:Alpha2.AT;
		case AZE:Alpha2.AZ;
		case BHS:Alpha2.BS;
		case BHR:Alpha2.BH;
		case BGD:Alpha2.BD;
		case BRB:Alpha2.BB;
		case BLR:Alpha2.BY;
		case BEL:Alpha2.BE;
		case BLZ:Alpha2.BZ;
		case BEN:Alpha2.BJ;
		case BMU:Alpha2.BM;
		case BTN:Alpha2.BT;
		case BOL:Alpha2.BO;
		case BIH:Alpha2.BA;
		case BWA:Alpha2.BW;
		case BVT:Alpha2.BV;
		case BRA:Alpha2.BR;
		case IOT:Alpha2.IO;
		case BRN:Alpha2.BN;
		case BGR:Alpha2.BG;
		case BFA:Alpha2.BF;
		case BDI:Alpha2.BI;
		case KHM:Alpha2.KH;
		case CMR:Alpha2.CM;
		case CAN:Alpha2.CA;
		case CPV:Alpha2.CV;
		case CYM:Alpha2.KY;
		case CAF:Alpha2.CF;
		case TCD:Alpha2.TD;
		case CHL:Alpha2.CL;
		case CHN:Alpha2.CN;
		case CXR:Alpha2.CX;
		case CCK:Alpha2.CC;
		case COL:Alpha2.CO;
		case COM:Alpha2.KM;
		case COG:Alpha2.CG;
		case COD:Alpha2.CD;
		case COK:Alpha2.CK;
		case CRI:Alpha2.CR;
		case CIV:Alpha2.CI;
		case HRV:Alpha2.HR;
		case CUB:Alpha2.CU;
		case CYP:Alpha2.CY;
		case CZE:Alpha2.CZ;
		case DNK:Alpha2.DK;
		case DJI:Alpha2.DJ;
		case DMA:Alpha2.DM;
		case DOM:Alpha2.DO;
		case ECU:Alpha2.EC;
		case EGY:Alpha2.EG;
		case SLV:Alpha2.SV;
		case GNQ:Alpha2.GQ;
		case ERI:Alpha2.ER;
		case EST:Alpha2.EE;
		case ETH:Alpha2.ET;
		case FLK:Alpha2.FK;
		case FRO:Alpha2.FO;
		case FJI:Alpha2.FJ;
		case FIN:Alpha2.FI;
		case FRA:Alpha2.FR;
		case GUF:Alpha2.GF;
		case PYF:Alpha2.PF;
		case ATF:Alpha2.TF;
		case GAB:Alpha2.GA;
		case GMB:Alpha2.GM;
		case GEO:Alpha2.GE;
		case DEU:Alpha2.DE;
		case GHA:Alpha2.GH;
		case GIB:Alpha2.GI;
		case GRC:Alpha2.GR;
		case GRL:Alpha2.GL;
		case GRD:Alpha2.GD;
		case GLP:Alpha2.GP;
		case GUM:Alpha2.GU;
		case GTM:Alpha2.GT;
		case GGY:Alpha2.GG;
		case GIN:Alpha2.GN;
		case GNB:Alpha2.GW;
		case GUY:Alpha2.GY;
		case HTI:Alpha2.HT;
		case HMD:Alpha2.HM;
		case VAT:Alpha2.VA;
		case HND:Alpha2.HN;
		case HKG:Alpha2.HK;
		case HUN:Alpha2.HU;
		case ISL:Alpha2.IS;
		case IND:Alpha2.IN;
		case IDN:Alpha2.ID;
		case IRN:Alpha2.IR;
		case IRQ:Alpha2.IQ;
		case IRL:Alpha2.IE;
		case IMN:Alpha2.IM;
		case ISR:Alpha2.IL;
		case ITA:Alpha2.IT;
		case JAM:Alpha2.JM;
		case JPN:Alpha2.JP;
		case JEY:Alpha2.JE;
		case JOR:Alpha2.JO;
		case KAZ:Alpha2.KZ;
		case KEN:Alpha2.KE;
		case KIR:Alpha2.KI;
		case PRK:Alpha2.KP;
		case KOR:Alpha2.KR;
		case KWT:Alpha2.KW;
		case KGZ:Alpha2.KG;
		case LAO:Alpha2.LA;
		case LVA:Alpha2.LV;
		case LBN:Alpha2.LB;
		case LSO:Alpha2.LS;
		case LBR:Alpha2.LR;
		case LBY:Alpha2.LY;
		case LIE:Alpha2.LI;
		case LTU:Alpha2.LT;
		case LUX:Alpha2.LU;
		case MAC:Alpha2.MO;
		case MKD:Alpha2.MK;
		case MDG:Alpha2.MG;
		case MWI:Alpha2.MW;
		case MYS:Alpha2.MY;
		case MDV:Alpha2.MV;
		case MLI:Alpha2.ML;
		case MLT:Alpha2.MT;
		case MHL:Alpha2.MH;
		case MTQ:Alpha2.MQ;
		case MRT:Alpha2.MR;
		case MUS:Alpha2.MU;
		case MYT:Alpha2.YT;
		case MEX:Alpha2.MX;
		case FSM:Alpha2.FM;
		case MDA:Alpha2.MD;
		case MCO:Alpha2.MC;
		case MNG:Alpha2.MN;
		case MNE:Alpha2.ME;
		case MSR:Alpha2.MS;
		case MAR:Alpha2.MA;
		case MOZ:Alpha2.MZ;
		case MMR:Alpha2.MM;
		case NAM:Alpha2.NA;
		case NRU:Alpha2.NR;
		case NPL:Alpha2.NP;
		case NLD:Alpha2.NL;
		case ANT:Alpha2.AN;
		case NCL:Alpha2.NC;
		case NZL:Alpha2.NZ;
		case NIC:Alpha2.NI;
		case NER:Alpha2.NE;
		case NGA:Alpha2.NG;
		case NIU:Alpha2.NU;
		case NFK:Alpha2.NF;
		case MNP:Alpha2.MP;
		case NOR:Alpha2.NO;
		case OMN:Alpha2.OM;
		case PAK:Alpha2.PK;
		case PLW:Alpha2.PW;
		case PSE:Alpha2.PS;
		case PAN:Alpha2.PA;
		case PNG:Alpha2.PG;
		case PRY:Alpha2.PY;
		case PER:Alpha2.PE;
		case PHL:Alpha2.PH;
		case PCN:Alpha2.PN;
		case POL:Alpha2.PL;
		case PRT:Alpha2.PT;
		case PRI:Alpha2.PR;
		case QAT:Alpha2.QA;
		case REU:Alpha2.RE;
		case ROU:Alpha2.RO;
		case RUS:Alpha2.RU;
		case RWA:Alpha2.RW;
		case SHN:Alpha2.SH;
		case KNA:Alpha2.KN;
		case LCA:Alpha2.LC;
		case SPM:Alpha2.PM;
		case VCT:Alpha2.VC;
		case WSM:Alpha2.WS;
		case SMR:Alpha2.SM;
		case STP:Alpha2.ST;
		case SAU:Alpha2.SA;
		case SEN:Alpha2.SN;
		case SRB:Alpha2.RS;
		case SYC:Alpha2.SC;
		case SLE:Alpha2.SL;
		case SGP:Alpha2.SG;
		case SVK:Alpha2.SK;
		case SVN:Alpha2.SI;
		case SLB:Alpha2.SB;
		case SOM:Alpha2.SO;
		case ZAF:Alpha2.ZA;
		case SGS:Alpha2.GS;
		case SSD:Alpha2.SS;
		case ESP:Alpha2.ES;
		case LKA:Alpha2.LK;
		case SDN:Alpha2.SD;
		case SUR:Alpha2.SR;
		case SJM:Alpha2.SJ;
		case SWZ:Alpha2.SZ;
		case SWE:Alpha2.SE;
		case CHE:Alpha2.CH;
		case SYR:Alpha2.SY;
		case TWN:Alpha2.TW;
		case TJK:Alpha2.TJ;
		case TZA:Alpha2.TZ;
		case THA:Alpha2.TH;
		case TLS:Alpha2.TL;
		case TGO:Alpha2.TG;
		case TKL:Alpha2.TK;
		case TON:Alpha2.TO;
		case TTO:Alpha2.TT;
		case TUN:Alpha2.TN;
		case TUR:Alpha2.TR;
		case TKM:Alpha2.TM;
		case TCA:Alpha2.TC;
		case TUV:Alpha2.TV;
		case UGA:Alpha2.UG;
		case UKR:Alpha2.UA;
		case ARE:Alpha2.AE;
		case GBR:Alpha2.GB;
		case USA:Alpha2.US;
		case UMI:Alpha2.UM;
		case URY:Alpha2.UY;
		case UZB:Alpha2.UZ;
		case VUT:Alpha2.VU;
		case VEN:Alpha2.VE;
		case VNM:Alpha2.VN;
		case VGB:Alpha2.VG;
		case VIR:Alpha2.VI;
		case WLF:Alpha2.WF;
		case ESH:Alpha2.EH;
		case YEM:Alpha2.YE;
		case ZMB:Alpha2.ZM;
		case ZWE:Alpha2.ZW;
	};
	@:to
	public function toAlpha3():Alpha3 return switch ((cast this : Numeric)) {
		case AFG:Alpha3.AFG;
		case ALB:Alpha3.ALB;
		case DZA:Alpha3.DZA;
		case ASM:Alpha3.ASM;
		case AND:Alpha3.AND;
		case AGO:Alpha3.AGO;
		case AIA:Alpha3.AIA;
		case ATA:Alpha3.ATA;
		case ATG:Alpha3.ATG;
		case ARG:Alpha3.ARG;
		case ARM:Alpha3.ARM;
		case ABW:Alpha3.ABW;
		case AUS:Alpha3.AUS;
		case AUT:Alpha3.AUT;
		case AZE:Alpha3.AZE;
		case BHS:Alpha3.BHS;
		case BHR:Alpha3.BHR;
		case BGD:Alpha3.BGD;
		case BRB:Alpha3.BRB;
		case BLR:Alpha3.BLR;
		case BEL:Alpha3.BEL;
		case BLZ:Alpha3.BLZ;
		case BEN:Alpha3.BEN;
		case BMU:Alpha3.BMU;
		case BTN:Alpha3.BTN;
		case BOL:Alpha3.BOL;
		case BIH:Alpha3.BIH;
		case BWA:Alpha3.BWA;
		case BVT:Alpha3.BVT;
		case BRA:Alpha3.BRA;
		case IOT:Alpha3.IOT;
		case BRN:Alpha3.BRN;
		case BGR:Alpha3.BGR;
		case BFA:Alpha3.BFA;
		case BDI:Alpha3.BDI;
		case KHM:Alpha3.KHM;
		case CMR:Alpha3.CMR;
		case CAN:Alpha3.CAN;
		case CPV:Alpha3.CPV;
		case CYM:Alpha3.CYM;
		case CAF:Alpha3.CAF;
		case TCD:Alpha3.TCD;
		case CHL:Alpha3.CHL;
		case CHN:Alpha3.CHN;
		case CXR:Alpha3.CXR;
		case CCK:Alpha3.CCK;
		case COL:Alpha3.COL;
		case COM:Alpha3.COM;
		case COG:Alpha3.COG;
		case COD:Alpha3.COD;
		case COK:Alpha3.COK;
		case CRI:Alpha3.CRI;
		case CIV:Alpha3.CIV;
		case HRV:Alpha3.HRV;
		case CUB:Alpha3.CUB;
		case CYP:Alpha3.CYP;
		case CZE:Alpha3.CZE;
		case DNK:Alpha3.DNK;
		case DJI:Alpha3.DJI;
		case DMA:Alpha3.DMA;
		case DOM:Alpha3.DOM;
		case ECU:Alpha3.ECU;
		case EGY:Alpha3.EGY;
		case SLV:Alpha3.SLV;
		case GNQ:Alpha3.GNQ;
		case ERI:Alpha3.ERI;
		case EST:Alpha3.EST;
		case ETH:Alpha3.ETH;
		case FLK:Alpha3.FLK;
		case FRO:Alpha3.FRO;
		case FJI:Alpha3.FJI;
		case FIN:Alpha3.FIN;
		case FRA:Alpha3.FRA;
		case GUF:Alpha3.GUF;
		case PYF:Alpha3.PYF;
		case ATF:Alpha3.ATF;
		case GAB:Alpha3.GAB;
		case GMB:Alpha3.GMB;
		case GEO:Alpha3.GEO;
		case DEU:Alpha3.DEU;
		case GHA:Alpha3.GHA;
		case GIB:Alpha3.GIB;
		case GRC:Alpha3.GRC;
		case GRL:Alpha3.GRL;
		case GRD:Alpha3.GRD;
		case GLP:Alpha3.GLP;
		case GUM:Alpha3.GUM;
		case GTM:Alpha3.GTM;
		case GGY:Alpha3.GGY;
		case GIN:Alpha3.GIN;
		case GNB:Alpha3.GNB;
		case GUY:Alpha3.GUY;
		case HTI:Alpha3.HTI;
		case HMD:Alpha3.HMD;
		case VAT:Alpha3.VAT;
		case HND:Alpha3.HND;
		case HKG:Alpha3.HKG;
		case HUN:Alpha3.HUN;
		case ISL:Alpha3.ISL;
		case IND:Alpha3.IND;
		case IDN:Alpha3.IDN;
		case IRN:Alpha3.IRN;
		case IRQ:Alpha3.IRQ;
		case IRL:Alpha3.IRL;
		case IMN:Alpha3.IMN;
		case ISR:Alpha3.ISR;
		case ITA:Alpha3.ITA;
		case JAM:Alpha3.JAM;
		case JPN:Alpha3.JPN;
		case JEY:Alpha3.JEY;
		case JOR:Alpha3.JOR;
		case KAZ:Alpha3.KAZ;
		case KEN:Alpha3.KEN;
		case KIR:Alpha3.KIR;
		case PRK:Alpha3.PRK;
		case KOR:Alpha3.KOR;
		case KWT:Alpha3.KWT;
		case KGZ:Alpha3.KGZ;
		case LAO:Alpha3.LAO;
		case LVA:Alpha3.LVA;
		case LBN:Alpha3.LBN;
		case LSO:Alpha3.LSO;
		case LBR:Alpha3.LBR;
		case LBY:Alpha3.LBY;
		case LIE:Alpha3.LIE;
		case LTU:Alpha3.LTU;
		case LUX:Alpha3.LUX;
		case MAC:Alpha3.MAC;
		case MKD:Alpha3.MKD;
		case MDG:Alpha3.MDG;
		case MWI:Alpha3.MWI;
		case MYS:Alpha3.MYS;
		case MDV:Alpha3.MDV;
		case MLI:Alpha3.MLI;
		case MLT:Alpha3.MLT;
		case MHL:Alpha3.MHL;
		case MTQ:Alpha3.MTQ;
		case MRT:Alpha3.MRT;
		case MUS:Alpha3.MUS;
		case MYT:Alpha3.MYT;
		case MEX:Alpha3.MEX;
		case FSM:Alpha3.FSM;
		case MDA:Alpha3.MDA;
		case MCO:Alpha3.MCO;
		case MNG:Alpha3.MNG;
		case MNE:Alpha3.MNE;
		case MSR:Alpha3.MSR;
		case MAR:Alpha3.MAR;
		case MOZ:Alpha3.MOZ;
		case MMR:Alpha3.MMR;
		case NAM:Alpha3.NAM;
		case NRU:Alpha3.NRU;
		case NPL:Alpha3.NPL;
		case NLD:Alpha3.NLD;
		case ANT:Alpha3.ANT;
		case NCL:Alpha3.NCL;
		case NZL:Alpha3.NZL;
		case NIC:Alpha3.NIC;
		case NER:Alpha3.NER;
		case NGA:Alpha3.NGA;
		case NIU:Alpha3.NIU;
		case NFK:Alpha3.NFK;
		case MNP:Alpha3.MNP;
		case NOR:Alpha3.NOR;
		case OMN:Alpha3.OMN;
		case PAK:Alpha3.PAK;
		case PLW:Alpha3.PLW;
		case PSE:Alpha3.PSE;
		case PAN:Alpha3.PAN;
		case PNG:Alpha3.PNG;
		case PRY:Alpha3.PRY;
		case PER:Alpha3.PER;
		case PHL:Alpha3.PHL;
		case PCN:Alpha3.PCN;
		case POL:Alpha3.POL;
		case PRT:Alpha3.PRT;
		case PRI:Alpha3.PRI;
		case QAT:Alpha3.QAT;
		case REU:Alpha3.REU;
		case ROU:Alpha3.ROU;
		case RUS:Alpha3.RUS;
		case RWA:Alpha3.RWA;
		case SHN:Alpha3.SHN;
		case KNA:Alpha3.KNA;
		case LCA:Alpha3.LCA;
		case SPM:Alpha3.SPM;
		case VCT:Alpha3.VCT;
		case WSM:Alpha3.WSM;
		case SMR:Alpha3.SMR;
		case STP:Alpha3.STP;
		case SAU:Alpha3.SAU;
		case SEN:Alpha3.SEN;
		case SRB:Alpha3.SRB;
		case SYC:Alpha3.SYC;
		case SLE:Alpha3.SLE;
		case SGP:Alpha3.SGP;
		case SVK:Alpha3.SVK;
		case SVN:Alpha3.SVN;
		case SLB:Alpha3.SLB;
		case SOM:Alpha3.SOM;
		case ZAF:Alpha3.ZAF;
		case SGS:Alpha3.SGS;
		case SSD:Alpha3.SSD;
		case ESP:Alpha3.ESP;
		case LKA:Alpha3.LKA;
		case SDN:Alpha3.SDN;
		case SUR:Alpha3.SUR;
		case SJM:Alpha3.SJM;
		case SWZ:Alpha3.SWZ;
		case SWE:Alpha3.SWE;
		case CHE:Alpha3.CHE;
		case SYR:Alpha3.SYR;
		case TWN:Alpha3.TWN;
		case TJK:Alpha3.TJK;
		case TZA:Alpha3.TZA;
		case THA:Alpha3.THA;
		case TLS:Alpha3.TLS;
		case TGO:Alpha3.TGO;
		case TKL:Alpha3.TKL;
		case TON:Alpha3.TON;
		case TTO:Alpha3.TTO;
		case TUN:Alpha3.TUN;
		case TUR:Alpha3.TUR;
		case TKM:Alpha3.TKM;
		case TCA:Alpha3.TCA;
		case TUV:Alpha3.TUV;
		case UGA:Alpha3.UGA;
		case UKR:Alpha3.UKR;
		case ARE:Alpha3.ARE;
		case GBR:Alpha3.GBR;
		case USA:Alpha3.USA;
		case UMI:Alpha3.UMI;
		case URY:Alpha3.URY;
		case UZB:Alpha3.UZB;
		case VUT:Alpha3.VUT;
		case VEN:Alpha3.VEN;
		case VNM:Alpha3.VNM;
		case VGB:Alpha3.VGB;
		case VIR:Alpha3.VIR;
		case WLF:Alpha3.WLF;
		case ESH:Alpha3.ESH;
		case YEM:Alpha3.YEM;
		case ZMB:Alpha3.ZMB;
		case ZWE:Alpha3.ZWE;
	};
	var AFG = 4;
	var ALB = 8;
	var DZA = 12;
	var ASM = 16;
	var AND = 20;
	var AGO = 24;
	var AIA = 660;
	var ATA = 10;
	var ATG = 28;
	var ARG = 32;
	var ARM = 51;
	var ABW = 533;
	var AUS = 36;
	var AUT = 40;
	var AZE = 31;
	var BHS = 44;
	var BHR = 48;
	var BGD = 50;
	var BRB = 52;
	var BLR = 112;
	var BEL = 56;
	var BLZ = 84;
	var BEN = 204;
	var BMU = 60;
	var BTN = 64;
	var BOL = 68;
	var BIH = 70;
	var BWA = 72;
	var BVT = 74;
	var BRA = 76;
	var IOT = 86;
	var BRN = 96;
	var BGR = 100;
	var BFA = 854;
	var BDI = 108;
	var KHM = 116;
	var CMR = 120;
	var CAN = 124;
	var CPV = 132;
	var CYM = 136;
	var CAF = 140;
	var TCD = 148;
	var CHL = 152;
	var CHN = 156;
	var CXR = 162;
	var CCK = 166;
	var COL = 170;
	var COM = 174;
	var COG = 178;
	var COD = 180;
	var COK = 184;
	var CRI = 188;
	var CIV = 384;
	var HRV = 191;
	var CUB = 192;
	var CYP = 196;
	var CZE = 203;
	var DNK = 208;
	var DJI = 262;
	var DMA = 212;
	var DOM = 214;
	var ECU = 218;
	var EGY = 818;
	var SLV = 222;
	var GNQ = 226;
	var ERI = 232;
	var EST = 233;
	var ETH = 231;
	var FLK = 238;
	var FRO = 234;
	var FJI = 242;
	var FIN = 246;
	var FRA = 250;
	var GUF = 254;
	var PYF = 258;
	var ATF = 260;
	var GAB = 266;
	var GMB = 270;
	var GEO = 268;
	var DEU = 276;
	var GHA = 288;
	var GIB = 292;
	var GRC = 300;
	var GRL = 304;
	var GRD = 308;
	var GLP = 312;
	var GUM = 316;
	var GTM = 320;
	var GGY = 831;
	var GIN = 324;
	var GNB = 624;
	var GUY = 328;
	var HTI = 332;
	var HMD = 334;
	var VAT = 336;
	var HND = 340;
	var HKG = 344;
	var HUN = 348;
	var ISL = 352;
	var IND = 356;
	var IDN = 360;
	var IRN = 364;
	var IRQ = 368;
	var IRL = 372;
	var IMN = 833;
	var ISR = 376;
	var ITA = 380;
	var JAM = 388;
	var JPN = 392;
	var JEY = 832;
	var JOR = 400;
	var KAZ = 398;
	var KEN = 404;
	var KIR = 296;
	var PRK = 408;
	var KOR = 410;
	var KWT = 414;
	var KGZ = 417;
	var LAO = 418;
	var LVA = 428;
	var LBN = 422;
	var LSO = 426;
	var LBR = 430;
	var LBY = 434;
	var LIE = 438;
	var LTU = 440;
	var LUX = 442;
	var MAC = 446;
	var MKD = 807;
	var MDG = 450;
	var MWI = 454;
	var MYS = 458;
	var MDV = 462;
	var MLI = 466;
	var MLT = 470;
	var MHL = 584;
	var MTQ = 474;
	var MRT = 478;
	var MUS = 480;
	var MYT = 175;
	var MEX = 484;
	var FSM = 583;
	var MDA = 498;
	var MCO = 492;
	var MNG = 496;
	var MNE = 499;
	var MSR = 500;
	var MAR = 504;
	var MOZ = 508;
	var MMR = 104;
	var NAM = 516;
	var NRU = 520;
	var NPL = 524;
	var NLD = 528;
	var ANT = 530;
	var NCL = 540;
	var NZL = 554;
	var NIC = 558;
	var NER = 562;
	var NGA = 566;
	var NIU = 570;
	var NFK = 574;
	var MNP = 580;
	var NOR = 578;
	var OMN = 512;
	var PAK = 586;
	var PLW = 585;
	var PSE = 275;
	var PAN = 591;
	var PNG = 598;
	var PRY = 600;
	var PER = 604;
	var PHL = 608;
	var PCN = 612;
	var POL = 616;
	var PRT = 620;
	var PRI = 630;
	var QAT = 634;
	var REU = 638;
	var ROU = 642;
	var RUS = 643;
	var RWA = 646;
	var SHN = 654;
	var KNA = 659;
	var LCA = 662;
	var SPM = 666;
	var VCT = 670;
	var WSM = 882;
	var SMR = 674;
	var STP = 678;
	var SAU = 682;
	var SEN = 686;
	var SRB = 688;
	var SYC = 690;
	var SLE = 694;
	var SGP = 702;
	var SVK = 703;
	var SVN = 705;
	var SLB = 90;
	var SOM = 706;
	var ZAF = 710;
	var SGS = 239;
	var SSD = 728;
	var ESP = 724;
	var LKA = 144;
	var SDN = 736;
	var SUR = 740;
	var SJM = 744;
	var SWZ = 748;
	var SWE = 752;
	var CHE = 756;
	var SYR = 760;
	var TWN = 158;
	var TJK = 762;
	var TZA = 834;
	var THA = 764;
	var TLS = 626;
	var TGO = 768;
	var TKL = 772;
	var TON = 776;
	var TTO = 780;
	var TUN = 788;
	var TUR = 792;
	var TKM = 795;
	var TCA = 796;
	var TUV = 798;
	var UGA = 800;
	var UKR = 804;
	var ARE = 784;
	var GBR = 826;
	var USA = 840;
	var UMI = 581;
	var URY = 858;
	var UZB = 860;
	var VUT = 548;
	var VEN = 862;
	var VNM = 704;
	var VGB = 92;
	var VIR = 850;
	var WLF = 876;
	var ESH = 732;
	var YEM = 887;
	var ZMB = 894;
	var ZWE = 716;
}